### ISSUE TITLE
Request: Breaking up the types.jl file

### ISSUE THREAD

**Issue by Lev-Stambler** [esabo/CodingTheory#20]
I understand the reasoning behind having types be in one file, but I was wondering if we could break up the types by topic and place them in their relevant subfolders considers that the type break up nicely. I am happy to do this and open a PR with this. I was thinking

src
.  Classical
.  . types.jl
. LDPC
. . types/
. . .  types_channels.jl
. . .  types_code.jl
. Quantum
. . types.jl

Open to suggestions. Am happy to take this up as well

**Comment by esabo** [comment]
They are only in a single file because the folders are relatively new. I'll look into breaking it up. Makes sense. Although, the module-level types may need to be kept outside in order to make it compile.
