### ISSUE TITLE
ERROR: MethodError: no method matching polynomial_ring(::ZZRing, ::Tuple{Symbol, Symbol})

### ISSUE THREAD

**Issue by cyanreg** [esabo/CodingTheory#21]
Happens when calling `LDPCCode()` with any matrix given as an argument.

Also, the examples haven't been updated yet either.

Replicatable on both the master and QWRv1 on Julia v1.10

**Comment by esabo** [comment]
Yeah, this is due to an update in a dep. I fixed it the other day on the dev branch, which also contains some fixes for other bugs introduced by the update. Please use dev until merged into master.

By examples you are referring to the documentation? That takes significant time to write and hasn't been done yet. On the list...

**Comment by esabo** [comment]
I've merged the fixes from dev into master. I'd say delete, try master again, and if it fails, please post the full stack trace.

**Comment by benide** [comment]
From your log it seems you're not using the Manifest.toml. Make sure you haven't updated that file and run `instantiate` in the package REPL from within the project environment.

**Comment by benide** [comment]
I was trying to find how to add it as a package while bringing in the manifest, but I'm not sure how that's done. We need to add some things to `[compat]` in Project.toml I think to make things work smoothly.

**Comment by esabo** [comment]
Ah, I see. The offending line is `  Installed Oscar ──────────────────────────── v0.14.0`. As Ben said, this is ignoring the Manifest file. I believe I have fixed it now by adding explicit version numbers to the Project file.

I didn't see why it would break in the function you specified, but the stacktrace shows it breaks in another function called by that, which makes sense. The Oscar v13 -> v14 update was a major breaking update. In this instance, v13 requires inputs to polynomial_ring in the form `(:x, :y)`, but v14 now requires `[:x, :y]`. These changes are currently being made in the up_deps branch.

**Comment by esabo** [comment]
and to get `GF` you need `using Oscar`

**Comment by benide** [comment]
The upshot is, @cyanreg, give `Pkg.add(url="https://github.com/esabo/CodingTheory")` another shot. It might work directly now without extra intervention.
