### ISSUE TITLE
Add `[compat]` entries to Project.toml for Oscar, etc.

### ISSUE THREAD

**Issue by benide** [esabo/CodingTheory#22]
It would be nice if `Pkg.add(url="https://github.com/esabo/CodingTheory")` worked directly. We'll need this before we can consider adding this package to the Julia registry anyway.

Biggest roadblock to easily adding the package as above is the current version of Oscar changed so many things. We should add a `[compat]` entry for it to Project.toml until we find time to make it work with the newer version. Probably need compat for a few other packages. #21 will be solved if we do this I think.

**Comment by esabo** [comment]
Done
