### ISSUE TITLE
Adding  quantum and classical versions of  `Convolutional` and `Block` codes

### ISSUE THREAD

**Issue by Fe-r-oz** [esabo/CodingTheory#33]
This paper by Grassl: https://arxiv.org/pdf/quant-ph/0703181 provides code constructions for the following codes:

- [ ] Quantum Block Codes
- [ ] Classical Block Codes ?
- [ ] Quantum Convoutional Codes
- [ ] Classical Convoutional Code

For a concise description of construction of classical convolutional codes using `free module`, `direct summands`, etc, follow this paper:  https://arxiv.org/pdf/quant-ph/0703113. Background Section `A: Convolutional Codes `

Another useful paper by Grassl and Rötteler is: https://arxiv.org/pdf/quant-ph/0703182

For a more thorough reference, this book, namely [Fundamentals of Convolutional Coding](https://www.wiley.com/en-us/Fundamentals+of+Convolutional+Coding%2C+2nd+Edition-p-9780470276839) might be helpful.

**Comment by esabo** [comment]
The current library is all block codes. There is no plan to add convolutional codes until block codes are much further developed, at best.

**Comment by Fe-r-oz** [comment]
Thank you for the insight!
