### ISSUE TITLE
Unit tests tweaks/cleanup

### ISSUE THREAD

**Issue by davidamarquis** [esabo/CodingTheory#38]
This will be a place for me to dump potential tweaks/cleanup about the unit tests as I go through the code. Ill write the items prescriptively to save time but they're notes to myself or things I want to ask about.

- Can we stop commenting out tests that don't pass now ?

File: Classical/concatentation.jl 
- Make functions for in the test cases to get rid of redundancy (can we just test n,k,d every time ?)
- References to textbooks like "Huffman and Pless, example 5.5.2" are good but I like code that's self contained. Add more details.

**Comment by esabo** [comment]
I'm happy for you to do whatever you think is best with respect to this.

**Comment by Fe-r-oz** [comment]
This is nice. There is a lot of redundancy in the tests  which can simply reduced via  loops. Also, using looping till random values of `n, k, d `might also help.
